"""HTML report generator for cashflow reconciliation.

Generates a self-contained HTML page with tables and summaries.
"""

from __future__ import annotations

from ..models import CashflowSummary


def generate_html_report(summary: CashflowSummary, title: str = "CEX Cashflow Report") -> str:
    """Generate a self-contained HTML report from a CashflowSummary."""
    exchange = summary.exchange.upper()
    currency = summary.currency

    def tr(k, v):
        return f"<tr><td style='padding:4px 12px;color:#8b949e'>{k}</td><td style='padding:4px 12px;font-weight:600'>{v}</td></tr>"

    match_rows = ""
    for i, m in enumerate(summary.matches[:50]):
        t = m.cex_record.tx_type.upper()
        amt = f"{m.cex_record.amount:.2f} {currency}"
        conf = f"{m.confidence * 100:.0f}%"
        mtype = m.match_type
        addr_short = m.cex_record.address[:16] + "..." if len(m.cex_record.address) > 16 else m.cex_record.address
        bg = "#1a2332" if i % 2 == 0 else "#0d1117"
        match_rows += f"""
        <tr style='background:{bg}'>
            <td style='padding:4px 8px'>{t}</td>
            <td style='padding:4px 8px'>{amt}</td>
            <td style='padding:4px 8px;font-size:11px'>{addr_short}</td>
            <td style='padding:4px 8px'>{conf}</td>
            <td style='padding:4px 8px'>{mtype}</td>
        </tr>"""

    unmatched_rows = ""
    for r in summary.unmatched_cex_records[:20]:
        addr_short = r.address[:16] + "..." if len(r.address) > 16 else r.address
        txid_str = r.txid[:12] + "..." if r.txid else "no txid"
        unmatched_rows += f"""
        <tr>
            <td style='padding:4px 8px'>{r.tx_type.upper()}</td>
            <td style='padding:4px 8px'>{r.amount:.2f} {currency}</td>
            <td style='padding:4px 8px;font-size:11px'>{addr_short}</td>
            <td style='padding:4px 8px;font-size:11px;color:#8b949e'>{txid_str}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8">
<title>{title} — {exchange}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
       background: #0d1117; color: #c9d1d9; margin: 0; padding: 20px; }}
h1 {{ color: #58a6ff; font-size: 24px; margin-bottom: 4px; }}
h2 {{ color: #c9d1d9; font-size: 18px; margin: 20px 0 10px; }}
.meta {{ color: #8b949e; font-size: 13px; margin-bottom: 20px; }}
.stats {{ display: flex; gap: 20px; margin-bottom: 20px; flex-wrap: wrap; }}
.stat-card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px;
              padding: 16px 20px; min-width: 140px; }}
.stat-card .label {{ font-size: 11px; color: #8b949e; text-transform: uppercase; }}
.stat-card .value {{ font-size: 24px; font-weight: 700; margin-top: 4px; }}
table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
th {{ text-align: left; padding: 8px; border-bottom: 2px solid #30363d; color: #8b949e; font-weight: 600; }}
td {{ padding: 8px; border-bottom: 1px solid #21262d; }}
.green {{ color: #3fb950; }}
.red {{ color: #f85149; }}
.yellow {{ color: #d29922; }}
</style>
</head>
<body>
<h1>{exchange} ↔ Cardano {currency} Cashflow</h1>
<div class="meta">Period: {summary.start_time} → {summary.end_time}</div>

<div class="stats">
  <div class="stat-card">
    <div class="label">Total Records</div>
    <div class="value">{summary.total_matches + summary.total_unmatched_cex}</div>
  </div>
  <div class="stat-card">
    <div class="label">Matched</div>
    <div class="value green">{summary.total_matches}</div>
  </div>
  <div class="stat-card">
    <div class="label">Unmatched</div>
    <div class="value red">{summary.total_unmatched_cex}</div>
  </div>
  <div class="stat-card">
    <div class="label">Match Rate</div>
    <div class="value">{summary.match_rate * 100:.1f}%</div>
  </div>
  <div class="stat-card">
    <div class="label">Inflow (matched)</div>
    <div class="value green">{summary.matched_inflow:.2f}</div>
  </div>
  <div class="stat-card">
    <div class="label">Outflow (matched)</div>
    <div class="value yellow">{summary.matched_outflow:.2f}</div>
  </div>
</div>

<h2>Matched Records ({len(summary.matches)})</h2>
<table>
<tr><th>Type</th><th>Amount</th><th>CEX Address</th><th>Confidence</th><th>Match Type</th></tr>
{match_rows}
</table>

<h2>Unmatched CEX Records ({len(summary.unmatched_cex_records)})</h2>
<table>
<tr><th>Type</th><th>Amount</th><th>Address</th><th>TXID</th></tr>
{unmatched_rows if unmatched_rows else '<tr><td colspan="4" style="color:#8b949e">None — all records matched</td></tr>'}
</table>

<div class="meta" style="margin-top:30px">
Generated by utxo-tracer · {summary.total_matches} matches, {summary.total_unmatched_cex} unmatched
</div>
</body>
</html>"""
    return html
